ExodusMovement/exodus-oss

- features/keychain/package.json
- package.json
- yarn.lock
depends on https://github.com/ExodusMovement/exodus-oss/pull/15
(updated)
6.0.0 -> 7.0.0 was technically a breaking change, but in practice just fixes crashes in serialization https://github.com/ExodusMovement/exodus-hydra/pull/4896
the 7.0.0 -> 7.0.1 patch is adding the missing `delay` dep, so no testing should be necessary
> refactor: bump atoms

- package.json
and remove postmigrate script until (if) we copy that one over
> **Note**
> No affected packages.
> chore: mv @exodus/migrate to devDeps

- .github/workflows/conflicts.yaml
- .github/workflows/label.yaml
bring back, lock down to commit hash
reverted in #26, but has now been reviewed
> chore: bring back label, merge conflict detection action

- features/keychain/module/__tests__/binauth.test.js
- features/keychain/module/__tests__/ecdsa.test.js
- features/keychain/module/__tests__/eddsa.test.js
- features/keychain/module/__tests__/example.integration-test.js
- features/keychain/module/__tests__/sodium.test.js
- features/keychain/module/crypto/ed25519.js
- features/keychain/module/crypto/secp256k1.js
- features/keychain/module/crypto/sodium.js
- features/keychain/module/keychain.js
Depends on: https://github.com/ExodusMovement/exodus-oss/pull/20
Don't panic about line changes 😄 Most of them are tests to ensure things work as expected
There are some keychain methods that do not adjust to the distributed architecture we are trying to push forward. These are:
- createSodiumEncryptor
- createEd15519Signer
- create Secp256k1Signer
This PR exposes the same apis in `keychain.sodium`, `keychain.ed15519` and `keychain.secp256k1`, without deprecating the old ones so we can gradually migrate. Main difference of these apis is we need to pass keyId to each method, which I think it's fine.
It's possible these new methods have a small performance regression given we previously reused the `sodium.getSodiumKeysFromSeed(privateKey)` instance. Not sure if this design decision was …
> feat(keychain)!: deprecate create methods

- .github/workflows/checks.yaml
- features/keychain/CHANGELOG.md
- features/keychain/package.json
- bump version
- update changelog
> chore: release @exodus/keychain 4.4.1 -> 5.0.0

- features/keychain/module/keychain.js
Calling `super.clear()` on child class does not work on arrow functions 😞
> fix(keychain): super.clear() call

- package.json
it's `log-level`, not `loglevel`. Today we get a warning in `format` and `format:check` scripts
> [warn] Ignored unknown option --loglevel=warn. Did you mean --log-level?
> chore: fix prettier log-level flag

- features/keychain/module/__tests__/key-identifier.test.js
- features/keychain/module/key-identifier.js
Add a `toString()` implementation to the key identifier that shows the derivation path and algorithm. Makes it more convenient to show key identifier information in logs or error messages. Not printing `assetName` as it is only needed for legacy use cases and the coin type part of the derivation path identifies the asset anyway.
> feat(key-identifier): add meaningful `toString()`

- features/keychain/CHANGELOG.md
- features/keychain/package.json
- yarn.lock
have to do this manually until we get lerna-release-action back
> chore: release keychain 6.0.0

- features/keychain/README.md
- features/keychain/module/__tests__/compatibility.test.js
- features/keychain/module/__tests__/eddsa.test.js
- features/keychain/module/__tests__/keychain.integration-test.js
- features/keychain/module/__tests__/sodium.test.js
- features/keychain/module/index.js
- features/keychain/module/validate.js
- features/keychain/package.json
- libraries/key-identifier/LICENSE
- libraries/key-identifier/README.md
- libraries/key-identifier/__tests__/key-identifier.integration-test.js
- libraries/key-identifier/__tests__/key-identifier.test.js
- libraries/key-identifier/babel.config.js
- libraries/key-identifier/jest.config.js
- libraries/key-identifier/package.json
- libraries/key-identifier/src/index.js
- libraries/key-identifier/src/key-identifier.js
- package.json
- yarn.lock
Extracts the key-identifier to a separate package (`@exodus/key-identifier`) for consumers that don't need or want to pull in the entire keychain. 
Closes https://github.com/ExodusMovement/exodus-hydra/issues/5725
1. run `yarn add @exodus/assets@latest @exodus/cardano-lib@^2.0.3 @exodus/ethereum-lib@^3.3.6 @exodus/models@^11.5.0 @exodus/solana-lib@^1.3.11 @exodus/solana-meta@^1.0.2 @exodus/storage-memory@^2.1.1` at the repo root
2. run `yarn todo:reenable:test:integration`, tests should pass
> feat: add separate key-identifier package

- features/keychain/module/keychain.js
currently callers of exodus.keychain.exportKey have to freeze the `keyId`, which is awkward and won't work over RPC
instead, we have the keychain freeze the keyId when exportKey is called
> fix: freeze internally in exportKey to callers don't have to

- features/keychain/module/__tests__/ethsign.test.js
- features/keychain/module/crypto/secp256k1.js
For signing ETH transactions we need to pass the `canonical` option to `ec.sign`. Also, using the DER format of the signature can be quite challenging as there is no simple function to pick it apart. With this change we can get the raw signature. It would be better if `signBuffer` didn't return the DER encoded value at all.
Fixtures for the new test were created using the ethereumjs library.
> feat: pass options to secp256k1 signBuffer

- features/keychain/module/keychain.js
- features/keychain/module/memoized-keychain.js
- features/keychain/package.json
- yarn.lock
Stop extending `ExodusModule` in keychain as we neither use the EventEmitter nor the logger part of it.
Not marking this as breaking because we never emitted events from keychain, so there cannot be any consumers.
> refactor: do not extend ExodusModule

- features/keychain/module/memoized-keychain.js
This PR resets the private property when calling `.clear()` for `@exodus/keychain` at version `5`.
Mirror of: #81
> fix: include memory cache on clear

- features/keychain/CHANGELOG.md
- features/keychain/package.json
Releases the `.clear()` fix from https://github.com/ExodusMovement/exodus-oss/pull/82 for v5.1, too.
> chore: release keychain 5.1.1

- .github/workflows/publish.yaml
- .github/workflows/version-dispatch.yaml
- .github/workflows/version.yaml
> chore: bring back lerna-release-action

- features/keychain/module/__tests__/schnorr.test.js
- features/keychain/module/crypto/secp256k1.js
- features/keychain/module/crypto/tweak.js
- features/keychain/package.json
- yarn.lock
Add support for schnorr signatures in secp256k1 signer
> feat: support for schnorr signatures

- features/keychain/README.md
Dummy PR to test branch protection rule settings
> docs: fix spelling

- libraries/key-identifier/__tests__/key-identifier.test.js
- libraries/key-identifier/package.json
- libraries/key-identifier/src/key-identifier.d.ts
- libraries/key-identifier/src/key-identifier.js
- yarn.lock
Add `derive` which accepts a partial derivation path and returns a new `KeyIdentifier` instance that has a derivation path that is extended with the supplied path indices.
Captured from https://github.com/ExodusMovement/exodus-hydra/pull/6497/files#r1575088966
> feat: add `keyIdentifier.derive()`

- features/keychain/api/__tests__/index.test.js
- features/keychain/module/__tests__/compatibility.test.js
- features/keychain/module/__tests__/ecdsa.test.js
- features/keychain/module/__tests__/eddsa.test.js
- features/keychain/module/__tests__/ethsign.test.js
- features/keychain/module/__tests__/lock-private-keys.test.js
- features/keychain/module/__tests__/schnorr.test.js
- features/keychain/module/crypto/ed25519.js
- features/keychain/module/crypto/secp256k1.js
This updates our signing functions to throw when they receive an invalid key type, i.e.:
- Schnorr and ECDSA require a secp256k1 key
- ED25519 requires a nacl key
Unfortunately we had many test cases where we provided key identifiers that were not valid for that particular signer (and therefore faild with the new assertion). I updated those
> feat: reject signing with invalid key types

- libraries/key-identifier/src/key-identifier.d.ts
Type was missing the `k` in `secp256k1`
> fix: type for `keyType` in `KeyIdentifier`

- features/keychain/module/__tests__/ecdsa.test.js
- features/keychain/module/crypto/secp256k1.js
This signature encoding seems to be popping up frequently. I'm wondering if we should include it here.
The binary encoding comes in handy so far for: filecoin, theta, tron, vechain, ...
> feat: add common signature encoding

- libraries/key-identifier/__tests__/key-identifier.test.js
- libraries/key-identifier/src/key-identifier.js
I was lead down a wrong path by a jest diff indicating that a key identifier I was dealing with was a pojo, even though it was a KeyIdentifier instance. This makes it clearer
> feat: use `KeyIdentifier` as string tag

- libraries/key-identifier/__tests__/key-identifier.test.js
- libraries/key-identifier/src/key-identifier.d.ts
- libraries/key-identifier/src/key-identifier.js
The latest `KeyIdentifier` stores a derivation path by its raw indicies in an array had a getter to return the stringified derivation path. The getter is not necessary as the derivation path is immutable, meaning it is sufficient to set it once on construction. It also gets in the way e.g. when using jest matchers.
> fix: ensure `derivationPath` is spreadable

- features/keychain/api/__tests__/index.test.js
- features/keychain/api/index.d.ts
- features/keychain/api/index.js
- features/keychain/module/__tests__/lock-private-keys.test.js
- features/keychain/module/crypto/seed-id.js
- features/keychain/module/keychain.js
As per our Zoom conversation, this PR implements a locked boolean flag per each seed individually, instead of using a single global flag for all seeds. 
This change allows for more granular control and flexibility in managing the locked status of each seed.
- The locked/unlocked state is now managed as a dictionary of `seedId -> boolean`
- All `keychain` internal operations that need to check whether or not the private keys are unlocked and accept a `seedId` via parameter now consider only the locked state of that seed before proceeding
- When a seed id cannot be inferred, or was not provided, all keys are checked and the check fails if any of them are locked
> feat: implement seed-specific locked boolean flag

- features/keychain/module/keychain.js
- features/keychain/module/memoized-keychain.js
In preparation for declaring registered dependencies private by default, this declares the keychain definitions as public.
> feat: declare keychain definitions as public

- libraries/key-identifier/src/key-identifier.js
This fixes the `isDerivationPath` predicate by using the correct `Symbol.toStringTag` getter syntax. Keeping the previous check for backwards compat as well.
> fix: `DerivationPath` predicate using `Symbol.toStringTag` getter

- libraries/key-identifier/__tests__/key-identifier.test.js
- libraries/key-identifier/package.json
- libraries/key-identifier/src/key-identifier.d.ts
- libraries/key-identifier/src/key-identifier.js
- yarn.lock
Add a way to access the `DerivationPath` instance used inside key identifier to store a derivation path. This allows for easier inspection/extraction of path indices required for certain use cases.
> feat: expose `DerivationPath` instance via getPath

- features/keychain/api/index.d.ts
- features/keychain/module/__tests__/example.integration-test.js
- features/keychain/module/keychain.js
With multi-seed, and now with the lock status of the seeds being managed individually, we need a way to remove only specific seeds from the keychain when those are deleted, this PR implements that.
> feat(keychain): implement removing specific seeds

- features/keychain/package.json
- jest.config.js
- yarn.lock
thanks @chalker for the issue and test plan 
```
import { fromMasterSeed as bip32FromMasterSeed } from '@exodus/bip32'
import SLIP10 from '@exodus/slip10'
const MAP_KDF = Object.freeze({
BIP32: bip32FromMasterSeed,
SLIP10: SLIP10.fromSeed,
})
console.log(Object.entries(MAP_KDF))
```
before: `[ [ 'BIP32', [Function: fromMasterSeed] ], [ 'SLIP10', undefined ] ]`
after: `[ [ 'BIP32', [Function: fromMasterSeed] ], [ 'SLIP10', [Function: fromSeed] ] ]`
> fix: upgrade slip10 to fix esm

- features/keychain/module/crypto/sodium.js
As noticed by @633kh4ck in [this comment](https://github.com/ExodusMovement/exodus-mobile/pull/21615#issuecomment-2348985772), the `exportPrivate` parameter is unused by `getPrivateHDKey`, so not really necessary.
The presence of this parameter also gives a false sense of security as devs looking at the current usage, since we don't have type validations when consuming that method, might assume that omitting that flag would avoid the private keys from being returned, which is not the case.
> refactor(keychain): drop unused getPrivateHDKey "exportPrivate" param

- features/keychain/module/__tests__/sodium.test.js
- features/keychain/module/crypto/sodium.js
Updates the `keychain` module so that `keychain.sodium.getSodiumKeysFromSeed` only returns the `secret` key when `exportSecret` is set.
The `secret` key holds the symmetric-key encryption key used in `libsodium` to both encrypt and decrypt messages, therefore its very sensitive data and shouldn't be exposed unless in very specific situations.
Closes: #136
> fix(keychain)!: only export secret if "exportPrivate" flag is set

- features/keychain/api/__tests__/index.test.js
- features/keychain/api/index.d.ts
- features/keychain/api/index.js
Expose `encryptSecretBox ` and `decryptSecretBox` through the keychain API
> feat: expose sodium encryption through API

- .eslintrc.js
- features/keychain/module/__tests__/schnorr.test.js
- features/keychain/module/crypto/secp256k1.js
- features/keychain/module/crypto/tweak.js
- features/keychain/package.json
- yarn.lock
The same underlying `noble` lib, but cleaner API + `utils.hmacSha256Sync` / `utils.sha256Sync` initialized
Also, we can use async for native sha256
> feat: switch to exodus/crypto for schnorr signatures

- features/keychain/api/__tests__/index.test.js
- features/keychain/api/index.d.ts
- features/keychain/module/__tests__/ecdsa.test.js
- features/keychain/module/__tests__/ethsign.test.js
- features/keychain/module/crypto/secp256k1.js
This removes `canonical` and `pers` elliptic options
`canonical` was set to `true` everywhere this was used (except tests in this repo), now it's just hardcoded to `true` instead of having to specify it everywhere
For example, both https://www.npmjs.com/package/tiny-secp256k1  and https://www.npmjs.com/package/secp256k do not even support generation of non-canonical signatures
`pers` was just merged in #146 and did not get into any release yet
I don't expect this to be realistically a breaking change to anything
This is a preparation to moving to `exodus/crypto` based on noble
A better alternative for `pers` option will be reintroduced
Test vectors were required to be updated by the `canonical` flip, so I also normalized them
> feat: remove ecOptions from secp256k1 signer

- features/keychain/package.json
- package.json
- tools/package.json
- yarn.lock
Towards using same lib versions in client
> refactor: bump basic-utils

- features/keychain/api/index.js
- features/keychain/module/crypto/sodium.js
This adds `sodium.getKeysFromSeed` for the keychain module, so that api and module have the same interface. Below is what we use in the api:
https://github.com/ExodusMovement/exodus-oss/blob/c1dd7e18a51e425440be3fdda60b3d9e0e3afca0/features/keychain/api/index.d.ts#L24-L26
This is relevant for the wallet process. Keeps `getSodiumKeysFromSeed` for backwards compat and deprecates it.
> feat: add `sodium.getKeysFromSeed`

- features/keychain/api/__tests__/index.test.js
- features/keychain/api/index.d.ts
- features/keychain/api/index.js
exposing `sodium.sign` is required for seedless
> feat: expose `sodium.sign`

- features/keychain/module/crypto/ed25519.js
- features/keychain/module/crypto/sodium.js
- features/keychain/package.json
- yarn.lock
Still uses sodium for boxes
Other methods are ported to `@exodus/crypto/curve25519`
Values (and their formats) are equivalent in-place
> feat: use exodus/crypto instead of sodium where possible

- features/keychain/api/__tests__/index.test.js
- features/keychain/api/index.js
- features/keychain/package.json
backfix of https://github.com/ExodusMovement/exodus-oss/pull/171 to be added on top of 7.4.0. Later 7.5.x is not ready for production yet
Not to merge, could we manually publish this?
> backfix: add signSchnorr to keychain api

- features/keychain/api/__tests__/index.test.js
- features/keychain/api/index.d.ts
- features/keychain/module/__tests__/schnorr.test.js
- features/keychain/module/crypto/secp256k1.js
This PR adds the missing schnorrSign ts type and fixes the return type to be `Buffer` rather than just `Uint8Array` for consistency
> fix: schnorrSign return type and type and signature

- features/keychain/api/__tests__/index.test.js
- features/keychain/api/index.d.ts
- features/keychain/module/keychain.js
This PR adds a `exportPublic` flag to the `exportKey` function which allows the consumer to skip the public key derivation which may be quite expensive.
> feat: add ability to skip public key generation

- .github/workflows/publish.yaml
- .github/workflows/version-dispatch.yaml
- .github/workflows/version.yaml
Update to the latest release action and refuse publishing from branches that are not protected by the default ruleset
> ci: update release action and only publish from protected branch

- features/keychain/module/__tests__/sign-buffer.test.js
- features/keychain/module/keychain.js
Copy the[ signing function from tx-signer](https://github.com/ExodusMovement/exodus-hydra/blob/500c4a9912cb01afe5a0b86a071f0ba13683f162/features/tx-signer/src/module/seed-signer.ts#L113), so that we don't need that much keychain detail knowledge in tx-signer. ~Looking for Conept ACK (initially).~
> feat: add signBuffer function

- features/keychain/api/__tests__/index.test.js
- features/keychain/api/index.js
@sparten11740 we need this for fusion when using the wallet-sdk. The keychain API needs to return the same values as the keychain module here: https://github.com/ExodusMovement/exodus-hydra/blob/e00af1ac93cb4462f5a7626da3b28a90fff916d1/sdks/headless/src/migrations/attach.js#L53
> fix: propagate all values from sodium.getKeysFromSeed via api

- libraries/key-identifier/src/key-identifier.js
together with https://github.com/ExodusMovement/exodus-hydra/pull/11707
allows to use KeyIdentifier in isolated processes on desktop that forbid require('crypto')
> fix: import derivation-path directly instead of all key-utils
